# ~/.config/yazi/keymap.toml

# Fix W key for opening shell
[[mgr.prepend_keymap]]
on   = ["W"]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# Alternative shell key if W doesn't work
[[mgr.prepend_keymap]]
on   = ["!"]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell"

# Quick preview with different tools
[[mgr.prepend_keymap]]
on   = ["i"]
run  = 'shell "viu \"$0\"" --block --confirm'
desc = "Quick image preview"

[[mgr.prepend_keymap]]
on   = ["P"]
run  = 'shell "termpdf.py \"$0\"" --block --confirm'
desc = "Quick PDF preview"
